import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/common/SideBar";
import TrialBanner from "@/components/common/TrialBanner";
import TrialEndedModal from "@/components/common/TrialEndedModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}>
      <TrialEndedModal />
      <Sidebar/>
      <div className="flex flex-col flex-1 min-w-0">
        <TrialBanner />
        {children}
      </div>
    </div>
  );
}
